require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/workshop/posts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Workshop::Post. As you add validations to Workshop::Post, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Workshop::Post.create! valid_attributes
      get workshop_posts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      post = Workshop::Post.create! valid_attributes
      get workshop_post_url(post)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_workshop_post_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      post = Workshop::Post.create! valid_attributes
      get edit_workshop_post_url(post)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Workshop::Post" do
        expect {
          post workshop_posts_url, params: { workshop_post: valid_attributes }
        }.to change(Workshop::Post, :count).by(1)
      end

      it "redirects to the created workshop_post" do
        post workshop_posts_url, params: { workshop_post: valid_attributes }
        expect(response).to redirect_to(workshop_post_url(Workshop::Post.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Workshop::Post" do
        expect {
          post workshop_posts_url, params: { workshop_post: invalid_attributes }
        }.to change(Workshop::Post, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post workshop_posts_url, params: { workshop_post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested workshop_post" do
        post = Workshop::Post.create! valid_attributes
        patch workshop_post_url(post), params: { workshop_post: new_attributes }
        post.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the workshop_post" do
        post = Workshop::Post.create! valid_attributes
        patch workshop_post_url(post), params: { workshop_post: new_attributes }
        post.reload
        expect(response).to redirect_to(workshop_post_url(post))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        post = Workshop::Post.create! valid_attributes
        patch workshop_post_url(post), params: { workshop_post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested workshop_post" do
      post = Workshop::Post.create! valid_attributes
      expect {
        delete workshop_post_url(post)
      }.to change(Workshop::Post, :count).by(-1)
    end

    it "redirects to the workshop_posts list" do
      post = Workshop::Post.create! valid_attributes
      delete workshop_post_url(post)
      expect(response).to redirect_to(workshop_posts_url)
    end
  end
end
